### ISSUE TITLE
How to contact you?

### ISSUE THREAD

**Issue by MKZIOOO** [larteyoh/neroshop#1]
Hello, i've been interested in marketplaces for a long, **i want to help you** if possible...
Here you have my discord: **MKZ#4452**
If you want to contact me using something safer or anonymous tell me.

**Comment by larteyoh** [comment]
Hey! I appreciate that there's someone out there who is also interested in marketplaces and wants to help me with my project. I don't really use discord (deleted it a while back), but I don't mind creating a new throwaway account if it's for the sake of this project. Other ways to contact me are Signal, Matrix/Element ([@layter:matrix.org](url)), Reddit ([https://www.reddit.com/user/jkinnof](url)). I can also be contacted via email ([larteyoh@pm.me](url)).
